version: "3"

services:
  db:
    image: "postgres:12.5"
    restart: "always"
    volumes:
      - "./docker_data/postgresql:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingester:
    build:
      context: ./ingester
      dockerfile: Dockerfile
    restart: "always"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: "always"
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
